---
title: "reading_data"
author: "Weijie Liu"
date: "October 25, 2017"
output: html_document

---


## Scraping

```{r}
library(tidyverse)
library(rvest)
library(httr)
```

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_xml = read_html(url)
```


That's step one!

```{r}
drug_use_xml %>%
  html_nodes(css = "table")


```

Got the tables
```{r}
table_marj = (drug_use_xml %>% html_nodes(css = "table"))[[1]] %>%
  html_table() %>%
  .[-1,] %>%
  as_tibble()

table_marj
```

## Practice!!!!!!!

```{r}
url = "https://www.bestplaces.net/cost_of_living/city/new_york/new_york"
nyc_cost = read_html(url)

```

```{r}
nyc_cost_table = (nyc_cost %>%
  html_nodes(css = "table"))[[2]] %>%
  html_table(header = TRUE)
  

```

## HP_SS Cast

I want the names!!!

```{r}
url = "http://www.imdb.com/title/tt0241527/"
hpss_xml = read_html(url)

hpss_cast = hpss_xml %>%
  html_nodes(css = ".itemprop .itemprop") %>%
  html_text()
```

## Toothbrush reviews

Dental hyggiene;;ksdf

```{r}
url = "https://www.amazon.com/Philips-Sonicare-rechargeable-toothbrush-HX6211/product-reviews/B00YAR7ZFM/ref=cm_cr_arp_d_viewopt_srt?ie=UTF8&reviewerType=all_reviews&sortBy=recent&pageNumber=1"

toothbrush_xml = read_html(url)

toothbrush_titles = toothbrush_xml %>%
  html_nodes(css = "#cm_cr-review_list .a-color-base") %>%
  html_text()

toothbrush_stars = toothbrush_xml %>%
  html_nodes(css = "#cm_cr-review_list .review-rating") %>%
  html_text()

toothbrush_df = data.frame(
  title = toothbrush_titles,
  stars = toothbrush_stars
) %>%
  View()
```







```{r}
nyc_water = GET("https://data.cityofnewyork.us/resource/waf7-5gvc.csv") %>%
    content("parsed")


```

Getting the data using JSON

```{r}
nyc_water = GET("https://data.cityofnewyork.us/resource/waf7-5gvc.json") %>% 
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()


```

```{r}

brfss = 
  GET("https://chronicdata.cdc.gov/api/views/hn4x-zwk7/rows.csv?accessType=DOWNLOAD") %>% 
  content("parsed")

```


```{r}
poke = GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

```